services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "K79OUIOj#.."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend
networks:
  backend:
